New-Item -Path ./data -Type Directory
New-Item -Path ./data/blacklist -Type Directory
New-Item -Path ./data/colornames -Type Directory
New-Item -Path ./data/gp -Type Directory
New-Item -Path ./data/infractions -Type Directory
New-Item -Path ./data/logchannel -Type Directory
New-Item -Path ./data/prefixes -Type Directory
New-Item -Path ./data/releases -Type Directory
New-Item -Path ./data/tags -Type Directory
New-Item -Path ./data/userdata -Type Directory