/**This file has not been tested but should work */
import { mkdir, existsSync, mkdirSync } from "fs";
import Enmap from "enmap";
import { join } from "path";

init();
//Dir();
async function Dir(): Promise<void> {
	await mkdirSync(join(__dirname, "..", "data"));
	await mkdirSync(join(__dirname, "..", "data", "blacklist"));
	await mkdirSync(join(__dirname, "..", "data", "colornames"));
	await mkdirSync(join(__dirname, "..", "data", "gp"));
	await mkdirSync(join(__dirname, "..", "data", "infractions"));
	await mkdirSync(join(__dirname, "..", "data", "logchannel"));
	await mkdirSync(join(__dirname, "..", "data", "mutes"));
	await mkdirSync(join(__dirname, "..", "data", "prefixes"));
	await mkdirSync(join(__dirname, "..", "data", "releases"));
	await mkdirSync(join(__dirname, "..", "data", "guilddata"));
	await mkdirSync(join(__dirname, "..", "data", "tags"));
	await mkdirSync(join(__dirname, "..", "data", "userData"));
}

function log() {
	console.log("[ LOADING DB FIRST TIME ]");
	console.log("[ DATABASE LOADED ]");
	console.log("[ PLEASE RESTART THE BOT ]");
	console.log("[ TO MAKE SURE EVERYTHING WENT THROUGH ]");
	console.log("[ REPO: https://github.com/SkyBlockDev/malil-akairo ]");
	console.log("[ DISCORD: https://discord.gg/mY8zTARu4g ]");
	console.log("[ WEBSITE:  https://tricked-dev.gitbook.io/malil/ ]");
}
async function innitialize() {
	const gp = await new Enmap({ name: "gp", dataDir: join(__dirname, "..", "data/gp") });
	const logchannel = new Enmap({ name: "logchannel", dataDir: join(__dirname, "..", "data/logchannel") });
	const tags = new Enmap({ name: "tags", dataDir: join(__dirname, "..", "data/tags") });
	const prefixes = new Enmap({ name: "prefixes", dataDir: join(__dirname, "..", "data/prefixes") });
	const blacklist = new Enmap({ name: "blacklist", dataDir: join(__dirname, "..", "data/blacklist") });
	const guilddata = new Enmap({ name: "guildata", dataDir: join(__dirname, "..", "data/guilddata") });
	const mutes = new Enmap({ name: "mutes", dataDir: join(__dirname, "..", "data/mutes") });
	const releases = new Enmap({ name: "releases", dataDir: join(__dirname, "..", "data/releases") });
	const infractions = new Enmap({ name: "infractions", dataDir: join(__dirname, "..", "data/infractions") });
	const UserData = new Enmap({ name: "users", dataDir: join(__dirname, "..", "data/userData") });
	await blacklist.ensure("blacklisted", [], "guilds");
	await blacklist.ensure("blacklisted", [], "list");
	await gp.ensure("superUsers", []);
	await blacklist.ensure("blacklist", [], "leavelist");
	await releases.ensure("all", []);
	await gp.ensure("commands", 0);
	await gp.ensure("shitpost", []);
}
async function init() {
	await Dir();
	log();
	innitialize();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
	log();
}
