name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.x'
      - name: Add config file
        run: cp src/example-settings.ts src/settings.ts
      - name: Install dependencies
        run: |
          yarn
      - name: Lint code
        run: |
          yarn lint

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.x'
      - name: Add config file
        run: cp src/example-settings.ts src/settings.ts
      - name: Install dependencies
        run: |
          yarn
      - name: Build code
        run: |
          yarn build
